# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BluePrintLAB Test Site
email: marketer@blueprint-lab.com
description: Jekyll test site for BluePrintLAB
baseurl: "/" # the subpath of your site, e.g. /blog
url: "bplmarketer.github.io" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-bold # Font Awesome class for your site's icon

# Social settings
facebook_url: https://www.facebook.com/blueprintlab4u/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/blueprintlab3d/
linkedin_url: https://www.linkedin.com/company/14509122
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
style: compressed

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
